# Generated by Django 6.0.4 on 2026-04-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_processing_error_video_processing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
