# Generated by Django 6.0.4 on 2026-05-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('water', 'Water'), ('mountains', 'Mountains'), ('trees', 'Trees'), ('animals', 'Animals'), ('buildings', 'Buildings'), ('soulfood', 'Soulfood'), ('beaches', 'Beaches'), ('flower', 'Flower'), ('miscellaneous', 'Miscellaneous')], max_length=50),
        ),
    ]
